### ISSUE TITLE
'version' Field in Extension's Manifest is Invalid

### ISSUE THREAD

**Issue by ArthurSudbrackIbarra** [vanflux/whatsapp-web-mod#1]
Actual:

```json
"version": "v1.4.0"
```

Correct way:

```json
"version": "1.4.0"
```

I fixed it manually for it to work, but your [latest release](https://github.com/vanflux/whatsapp-web-mod/releases/tag/v1.4.0) is broken because of this error. 😃

**Comment by vanflux** [comment]
Thanks, will be fixed in next release.

**Comment by vanflux** [comment]
> Actual:
> 
> ```json
> "version": "v1.4.0"
> ```
> 
> Correct way:
> 
> ```json
> "version": "1.4.0"
> ```
> 
> I fixed it manually for it to work, but your [latest release](https://github.com/vanflux/whatsapp-web-mod/releases/tag/v1.4.0) is broken because of this error. 😃

Can you check if the error persists now?
